//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaIntermedioPackinMicroplus {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class SettingsConexion : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsConexion defaultInstance = ((SettingsConexion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsConexion())));
        
        public static SettingsConexion Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=82.163.176.103;user id=smartbu2_jl;password=gu)1!0i4Sp;database=smartbu2_j" +
            "l;SSL Mode=None")]
        public string conexionMySql {
            get {
                return ((string)(this["conexionMySql"]));
            }
            set {
                this["conexionMySql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=db_microplus_32;uid=dba;pwd=AdminSQLplus.-18460")]
        public string conexionSybase {
            get {
                return ((string)(this["conexionSybase"]));
            }
            set {
                this["conexionSybase"] = value;
            }
        }
    }
}
